import { Router } from 'express';
import authRoutes from './authRoutes.js';
import dashboardRoutes from './dashboardRoutes.js';
import employeeRoutes from './employeeRoutes.js';
import attendanceRoutes from './attendanceRoutes.js';
import clientRoutes from './clientRoutes.js';
import taskRoutes from './taskRoutes.js';
import profileRoutes from './profileRoutes.js';
import openingRoutes from './openingRoutes.js';
import reportRoutes from './reportRoutes.js';
import leaveRoutes from './leaveRoutes.js';
import candidateRoutes from './candidateRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import invoiceRoutes from './invoiceRoutes.js';
import attendanceCorrectionRoutes from './attendanceCorrectionRoutes.js';
import holidayRoutes from './holidayRoutes.js';
import appUpdateRoutes from './appUpdateRoutes.js';
import onboardingRoutes from './onboardingRoutes.js';
import employeeOnboardingRoutes from './employeeOnboardingRoutes.js';
import companyRoutes from './companyRoutes.js';
import platformRoutes from './platformRoutes.js';
import activationCodeRoutes from './activationCodeRoutes.js';
import accessRoutes from './accessRoutes.js';
import payrollRoutes from './payrollRoutes.js';
import assetRoutes from './assetRoutes.js';
import accessRequestRoutes from './accessRequestRoutes.js';
import companyConfigRoutes from './companyConfigRoutes.js';

const router = Router();

router.use('/auth', authRoutes);
// Public company setup (status / validate-activation / register-company) must
// be mounted before employee onboarding, which requires authentication.
router.use('/onboarding', onboardingRoutes);
router.use('/onboarding', employeeOnboardingRoutes);
router.use('/company', companyRoutes);
router.use('/platform', platformRoutes);
router.use('/activation-codes', activationCodeRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/employees', employeeRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/clients', clientRoutes);
router.use('/tasks', taskRoutes);
router.use('/profile', profileRoutes);
router.use('/openings', openingRoutes);
router.use('/reports', reportRoutes);
router.use('/leave', leaveRoutes);
router.use('/candidates', candidateRoutes);
router.use('/notifications', notificationRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/attendance-corrections', attendanceCorrectionRoutes);
router.use('/holidays', holidayRoutes);
router.use('/app-updates', appUpdateRoutes);
router.use('/access', accessRoutes);
router.use('/payroll', payrollRoutes);
router.use('/assets', assetRoutes);
router.use('/access-requests', accessRequestRoutes);
router.use('/company-config', companyConfigRoutes);

export default router;